[bindings]
root.move_up = ["k", "up"]
root.move_down = ["j", "down"]
root.move_up_line = ["ctrl+k", "alt+up"]
root.move_down_line = ["ctrl+j", "alt+down"]
root.move_prev_section = ["alt+k"]
root.move_next_section = ["alt+j"]
